{
 "title": "Pipeline environments overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{\n  namespace=~\"dev|staging|prod\",\n  container=\"cicd-pipeline-app\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"dev|staging|prod\", container=\"cicd-pipeline-app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"cicd-pipeline-app\", namespace=~\"dev|staging|prod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}